<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		
		<Title>Sandev Library</Title>
		<Description>Reusable library for .NET 8, 9, and 10</Description>
		<Authors>Irsan Iskandar</Authors>
		<Company>Irsan.Dev</Company>
		
		<AssemblyVersion>2.6.0</AssemblyVersion>
		<FileVersion>2.6.0</FileVersion>
		<Version>2.6.0</Version>
		
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Nullable>enable</Nullable>
		<PackageTags>EFCore;Dapper;Utility;SecurityAlgorithm;Enryption;Decryption;</PackageTags>
	</PropertyGroup>
	
	<PropertyGroup>
		<PackageId>Sandev.Library</PackageId>
		<RepositoryUrl>https://github.com/IrsanIskandar/SandevLibrary</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/IrsanIskandar/SandevLibrary</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.*" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
		<PackageReference Include="Newtonsoft.Json" Version="13.*" />
		<PackageReference Include="NPOI" Version="2.*" />
		<PackageReference Include="RestSharp" Version="113.*" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.*" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*" PrivateAssets="all" />
	</ItemGroup>

	<!--<ItemGroup>
		<Content Include="Asset\lib\**\*.*">
			<Link>runtimes\%(RecursiveDir)%(FileName)%(Extension)</Link>
			<PublishState>Included</PublishState>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>true</Pack>
			<Visible>False</Visible>
			<IncludeInVsix>true</IncludeInVsix>
		</Content>
	</ItemGroup>-->
	<Target Name="IronPdfChromeWindowsBuild" BeforeTargets="Build">
		<Message Text="Copying IronPdf files from Asset\lib\runtimes to build directory for .NET Framework on Windows..." Importance="high" />
		<ItemGroup>
			<RuntimesNativeLibsBuild Include="Asset\lib\**\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(RuntimesNativeLibsBuild)" DestinationFolder="$(OutputPath)runtimes\%(RecursiveDir)" />
	</Target>

	<ItemGroup>
		<Reference Include="BitMiracle.LibTiff.NET">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\BitMiracle.LibTiff.NET.dll</HintPath>
		</Reference>
		<Reference Include="IronPdf">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\IronPdf.dll</HintPath>
		</Reference>
		<Reference Include="IronSoftware.Drawing.Common">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\IronSoftware.Drawing.Common.dll</HintPath>
		</Reference>
		<Reference Include="IronXL">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironxl.excel\2022.12.11262\lib\netstandard2.0\IronXL.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Extensions.Logging.Abstractions">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Win32.SystemEvents">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\Microsoft.Win32.SystemEvents.dll</HintPath>
		</Reference>
		<Reference Include="SixLabors.Fonts">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\SixLabors.Fonts.dll</HintPath>
		</Reference>
		<Reference Include="SixLabors.ImageSharp">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\SixLabors.ImageSharp.dll</HintPath>
		</Reference>
		<Reference Include="SixLabors.ImageSharp.Drawing">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\SixLabors.ImageSharp.Drawing.dll</HintPath>
		</Reference>
		<Reference Include="System.Drawing.Common">
			<HintPath>..\..\..\..\..\PublishLibrary\SandevSupportLibrary\IronLibrary\CrackedByIrsan\ironpdf\2023.1.11416\lib\netstandard2.0\System.Drawing.Common.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
